<?
$dbhost="localhost";
$dbuser="root";
$dbpass="";
$dbname="ftVine";
$path="E:\\xampp\\htdocs\\xampp\\Vis_web3152007\\backend\\backup\\";
$table0="content";
$table1="customer";
$table2="menu";
$table3="product";
$table4="productarea";
$table5="productcategory";
$table6="productcategoryinfamily";
$table7="productfamily";
$table8="productsubcategory";
$table9="productsubcategoryinfamily";
$table10="useraccount";
$numtables="10";
?>
